apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcp-ads-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gcp-ads-service
  template:
    metadata:
      labels:
        app: gcp-ads-service
    spec:
      containers:
        - name: app
          image: IMAGE_TO_DEPLOY
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: gcp-ads-service
spec:
  selector:
    app: gcp-ads-service
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080