pipeline {
    parameters {
        string(name: 'REGION', defaultValue: 'eu-central-1', description: 'AWS region for CloudFormation deployment')
        string(name: 'TEMPLATE_FILE_NAME', defaultValue: 'networks', description: 'Name of CloudFormation template file')
        string(name: 'GITHUB_REPO', defaultValue: 'eduardbalakh/AWSlabs', description: 'Repo with cloudformation templates')
    }

    agent any

    environment {
        AWS_REGION = "${params.REGION}"
        STACK_NAME = 'my-stack'
        GITHUB_REPO = "${params.GITHUB_REPO}"
        TEMPLATE_FILE = "${params.TEMPLATE_FILE_NAME}"
        PARAMS_FILE = "${params.TEMPLATE_FILE_NAME}-params.json"
        PIPELINE_FILE = 'Jenkinsfile'
        TAG = "${BUILD_NUMBER}"
    }

    stages {
        stage('Hello') {
            steps {
                sh "echo $PATH"
            }
        }

        stage('Build with MVN') {
            steps {
                sh "/usr/local/apache-maven-3.6.3/bin/mvn clean install package"
            }
        }

        stage('Build image') {
            steps {
                sh """docker build --tag eduardbalakh/adsservice:${TAG} ."""
            }
        }

        stage('Push image to Docker Hub') {
            steps {
                sh """docker push eduardbalakh/adsservice:${TAG}"""
            }
        }

        stage('Change version in template') {
            steps {
                script {
                    def imageVersion = "${TAG}"
                    sh "echo ${imageVersion}"
                    sh 'cat aws/adsservice-params.json'
                    sh 'cp aws/adsservice-params.json ${WORKSPACE}/params.json'
                    sh 'echo FILE AFTER update'
                    sh "sed -i 's/%imageVersion%/${imageVersion}/g' params.json"
                    sh 'cat params.json'
                }
            }
        }

        stage('Update AWS resources') {
            steps {
                build job: 'CloudFormation_install', parameters: [
                    string(name: 'GITHUB_REPO', value: 'eduardbalakh/gcp-ads-service'),
                    string(name: 'REGION', value: 'eu-central-1'),
                    string(name: 'TEMPLATE_FILE_NAME', value: 'adsservice')
                ]
            }
        }
    }
}