name: Build And Deploy To GKE

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{secrets.GKE_PROJECT}}
  GKE_CLUSTER: ${{secrets.GKE_CLUSTER}}
  GKE_CLUSTER_ZONE: ${{secrets.GKE_CLUSTER_ZONE}}
  DEPLOYMENT_NAME: ads-service
  IMAGE: ${{secrets.IMAGE_NAME}}
  TAG: ${{github.run_number}}
  FULL_IMAGE_NAME: ${{secrets.FULL_IMAGE_NAME}}

jobs:
  setup-build-publish-deploy:
    name: Setup Build Publish Deploy
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup java 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          server-id: github
          settings-path: ${{github.workspace}}

      - name: FAIL STEP
        run: exit 1

      - name: Build with Maven
        run: mvn clean package -q

      - name: Setup Google Cloud CLI
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@0.1.3
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        with:
          service_account_key: ${{secrets.GKE_SA_KEY}}
          project_id: ${{secrets.GKE_PROJECT}}

      - name: Configure Docker
        run: |-
          gcloud --quiet auth configure-docker

      - name: Get GKE credentials
        run: |-
          gcloud container clusters get-credentials "$GKE_CLUSTER" --zone="$GKE_CLUSTER_ZONE"

      - name: Build Docker image
        run: |-
          docker build --tag "gcr.io/$PROJECT_ID/$IMAGE:$TAG" .

      - name: Publish image to GCR
        run: |-
          docker push "gcr.io/$PROJECT_ID/$IMAGE:$TAG"

      - name: Replace image in config
        run: |-
          sed -i 's@IMAGE_TO_DEPLOY@${{secrets.FULL_IMAGE_NAME}}:${{github.run_number}}@g' kube.yaml
          cat kube.yaml
          kubectl get pods

      - name: Deploy to GKE
        run: |-
          kubectl apply -f kube.yaml

      - name: Send FAILURE notification to Telegram
        if: ${{ failure() }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHANNEL_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            🚫 FAIL 🚫
            JOB ID: ${{ github.run_number }}
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}
            
            Repository: ${{ github.repository }}
            
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}

      - name: Send SUCCESS notification to Telegram
        if: ${{ success() }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHANNEL_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            ✅ SUCCESS ✅
            JOB ID: ${{ github.run_number }}
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}
            
            Repository: ${{ github.repository }}
            
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}


